//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nite_Opps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nite_Opps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slew to Object,ngc2070,,,,
        ///Light Frame,,Lum,1,20,3
        ///Pause,,,,3,
        ///Slew to Object,M83,,,,
        ///Pause,,,,3,
        ///Light Frame,,Red,1,10,5
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///Empty,,,,,
        ///.
        /// </summary>
        internal static string arrayfile {
            get {
                return ResourceManager.GetString("arrayfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 , 0.150483482498897 , 27.7827516217532
        ///2 , 0.19302879495268 , -12.7608705288975
        ///3 , 0.21119293060793 , -0.352796666916685
        ///4 , 0.233759335666546 , 17.5487627225412
        ///5 , 0.302501932672509 , -9.48141547518444
        ///6 , 0.324763557454429 , -3.21446707425336
        ///7 , 0.324316353038462 , 10.6577084578956
        ///8 , 0.326902790733513 , -3.16030070486345
        ///9 , 0.338378475854689 , -14.0602954104457
        ///10 , 0.350030299316375 , 59.3579881407986
        ///11 , 0.893979066059399 , 56.6863150429351
        ///12 , 0.347073162386077 , -2.59168934787588        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IC_Database1_1529 {
            get {
                return ResourceManager.GetString("IC_Database1_1529", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 , 5.58723027491915 , 22.0215456625254
        ///2 , 21.5670604078068 , -0.773414196781935
        ///3 , 13.7121721617318 , 28.3144100311298
        ///4 , 16.4049212355622 , -26.5503008667797
        ///5 , 15.3191577218198 , 2.03963015880848
        ///6 , 17.6837166514512 , -32.2712961969198
        ///7 , 17.9086893287045 , -34.7840554937348
        ///8 , 18.0748871796389 , -24.382232400407
        ///9 , 17.3310455413071 , -18.5275050453086
        ///10 , 16.9625012203312 , -4.117900304373
        ///11 , 18.8617006307614 , -6.25411293889674
        ///12 , 16.7972479164132 , -1.96907964751188
        ///13 , 16.70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Messier_Database1_110 {
            get {
                return ResourceManager.GetString("Messier_Database1_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 , 0.130637447153745 , 27.7724754011345
        ///2 , 0.130971009211976 , 27.7421953290715
        ///3 , 0.130873274409962 , 8.36383360841337
        ///4 , 0.133012740080877 , 8.4363367600696
        ///5 , 0.139779314059887 , 35.4268373207078
        ///6 , 0.16863707870218 , 33.3728219820432
        ///7 , 0.148473910688585 , -29.8555884178005
        ///8 , 0.155484382571142 , 23.9019600300188
        ///9 , 0.158041329411436 , 23.8811245730484
        ///10 , 0.152219320256109 , -33.7970792579865
        ///11 , 0.15465204656596 , 37.5122453479263
        ///12 , 0.155314756177682 , 4.6744547205364
        ///13 , 0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database1_999 {
            get {
                return ResourceManager.GetString("NGC_Database1_999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 , 2.6592164696364 , 41.5114205254549
        ///1001 , 2.66560074808908 , 41.7227641019881
        ///1002 , 2.66037173376468 , 34.6724497077281
        ///1003 , 2.66664716833617 , 40.923791403168
        ///1004 , 2.63804932738973 , 2.02321968507001
        ///1005 , 2.6697562754211 , 41.5443718981653
        ///1006 , 2.63550940646617 , -10.97869951167
        ///1007 , 2.64097490966922 , 2.2032048354271
        ///1008 , 2.64180473040367 , 2.12791136632097
        ///1009 , 2.64839981060305 , 2.35758419029399
        ///1010 , 2.63550940646617 , -10.97869951167
        ///1011 , 2.63662136710256 , -10.9584 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database1000_1999 {
            get {
                return ResourceManager.GetString("NGC_Database1000_1999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000 , 5.45549865590436 , -71.8756055035559
        ///2001 , 5.48324419567428 , -68.7660509574885
        ///2002 , 5.50593984015823 , -66.881132791062
        ///2003 , 5.51557382430705 , -66.4635034559338
        ///2004 , 5.51127724544907 , -67.2831638192411
        ///2005 , 5.50179149431261 , -69.7494074150963
        ///2006 , 5.52234129253123 , -66.9691722776423
        ///2007 , 5.58786501973843 , -50.919686566826
        ///2008 , 5.5892184157357 , -50.9641538004452
        ///2009 , 5.51553832377383 , -69.1787944709763
        ///2010 , 5.50781361982921 , -70.8167295435957
        ///2011 , 5.53893685525 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database2000_2999 {
            get {
                return ResourceManager.GetString("NGC_Database2000_2999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000 , 9.82679096084424 , 44.0765199541136
        ///3001 , 9.78066436752552 , -30.492231842969
        ///3002 , 9.82842222984034 , 44.0015026032212
        ///3003 , 9.82175667175108 , 33.3665839837031
        ///3004 , 9.82981453522283 , 44.0564901884492
        ///3005 , 9.83336828734169 , 44.0753438684221
        ///3006 , 9.83399703950255 , 43.9703342135087
        ///3007 , 9.80589600385131 , -6.49345387359708
        ///3008 , 9.83869406088789 , 44.0475112935025
        ///3009 , 9.84900668575891 , 44.2399153252639
        ///3010 , 9.85547549036587 , 44.2681831604593
        ///3011 , 9.83978249555016 , 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database3000_3999 {
            get {
                return ResourceManager.GetString("NGC_Database3000_3999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000 , 11.9760215355718 , 25.0768738009243
        ///4001 , 11.9788526567675 , 47.2678727200548
        ///4002 , 11.9766536863569 , 23.1358188294893
        ///4003 , 11.976569688202 , 23.0583207472546
        ///4004 , 11.9782810720261 , 27.8115212098947
        ///4005 , 11.9796311813396 , 25.0552066362755
        ///4006 , 11.9784413352484 , -2.18622551044613
        ///4007 , 11.9796311813396 , 25.0552066362755
        ///4008 , 11.9816133233922 , 28.1256773281012
        ///4009 , 11.9810194304745 , 25.1238147505106
        ///4010 , 11.9872859608698 , 47.1928656803704
        ///4011 , 11.9839061538652 , 25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database4000_4999 {
            get {
                return ResourceManager.GetString("NGC_Database4000_4999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000 , 13.1725899762757 , 28.8418532086062
        ///5001 , 13.1676782152875 , 53.42861148819
        ///5002 , 13.1864420369471 , 36.5691083872505
        ///5003 , 13.1527918215955 , 43.6717961176701
        ///5004 , 13.1931125949841 , 29.5719157909663
        ///5005 , 13.1913957937378 , 36.9935608547531
        ///5006 , 13.2065650187778 , -19.3228875525563
        ///5007 , 13.1618881999869 , 62.1096345715492
        ///5008 , 14.1914056293695 , 25.4386031419371
        ///5009 , 13.1884295960312 , 50.0276415059853
        ///5010 , 13.2177534540364 , -15.8592072974449
        ///5011 , 13.2257316436959 , -4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database5000_5999 {
            get {
                return ResourceManager.GetString("NGC_Database5000_5999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6000 , 15.8422566788727 , -29.4205182753202
        ///6001 , 15.8039751154307 , 28.6023399372053
        ///6002 , 15.8035334075528 , 28.571224261561
        ///6003 , 15.8323787306585 , 18.9942563741998
        ///6004 , 15.8482683144366 , 18.9014333723856
        ///6005 , 15.945727760488 , -57.4667762853934
        ///6006 , 15.8930896647083 , 11.9690180090579
        ///6007 , 15.8988415531758 , 11.9229924342408
        ///6008 , 15.8906297821516 , 21.0635364314021
        ///6009 , 15.8990844959031 , 12.0215992962739
        ///6010 , 15.9150475038767 , 0.507575307678908
        ///6011 , 15.7744899895808 , 7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database6000_6999 {
            get {
                return ResourceManager.GetString("NGC_Database6000_6999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7000 , 20.9869055648107 , 44.5592900772426
        ///7001 , 21.0282919409627 , -0.151249732571138
        ///7002 , 21.0752105762597 , -48.9835414766796
        ///7003 , 21.0202408151704 , 17.8477967400981
        ///7004 , 21.0799382278385 , -49.0684861455834
        ///7005 , 21.0426521721252 , -12.836030968066
        ///7006 , 21.0334517862067 , 16.231309423075
        ///7007 , 21.1041504965641 , -52.5058709971283
        ///7008 , 21.0140991327468 , 54.5869895290265
        ///7009 , 21.0797316158266 , -11.3187059718522
        ///7010 , 21.0877244766964 , -12.2933107808589
        ///7011 , 21.036608208163 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NGC_Database7000_7840 {
            get {
                return ResourceManager.GetString("NGC_Database7000_7840", resourceCulture);
            }
        }
    }
}
